### ISSUE TITLE
Bug: Unable to use Macros for Filter Toggles.

### ISSUE THREAD

**Issue by Nanu308** [SpaiR/StrongDMM#116]
### Version

V2.0.0.alpha

### What happened?

Unable to use the macros for toggling the filters for Area, Mobs, Turfs, etc. which leads to a bad experience.

### Reproduction

1. Launch SDMM
2. Load up a DME
3. Try and use CTRL+1, CTRL+2, etc.
4. No filters change.

### Relevant log output

```bash
"There was an error creating your issue: body is too long (maximum is 65536 characters)."

Pastebin Link instead.
https://pastebin.com/pdpPHkzn
```

**Comment by SpaiR** [comment]
Hotkeys in StrongDMM have scopes. For example, when you are focusing a map canvas - you'll be able to use one hotkeys. When focusing a vareditor panel - other. From your logs I can see that you were calling for ctrl+1/2/3/4 when the vareditor panel was focused. To do what you want to do you need to focus the canvas at first. Please, verify that.

**Comment by Nanu308** [comment]
> Hotkeys in StrongDMM have scopes. For example, when you are focusing a map canvas - you'll be able to use one hotkeys. When focusing a vareditor panel - other. From your logs I can see that you were calling for ctrl+1/2/3/4 when the vareditor panel was focused. To do what you want to do you need to focus the canvas at first. Please, verify that.

Double checked, did not work either this time unless i am doing something wrong in regards to selecting the window.

https://pastebin.com/rpRdQFB7
