### ISSUE TITLE
Feature Request: Right Click Menu Enhancements

### ISSUE THREAD

**Issue by Nanu308** [SpaiR/StrongDMM#117]
### Problem to be solved

Changing Direction and Pixel offset on things from Right Click Menu.

### Sugest a solution

Be able to change dir and pixel offset from the right click menu like in the old SDMM

**Comment by SpaiR** [comment]
In v2.0.0.alpha you can change either dir or pixel offset with a quick edit menu. To see it just select an instance of the object on the map. I believe it's a more straightforward way to do that.

<img width="1099" alt="Screenshot 2022-03-01 at 20 44 27" src="https://user-images.githubusercontent.com/12721311/156237663-2171edaa-a266-4f0e-8db0-85c4b6c85cc8.png">

**Comment by Nanu308** [comment]
> In v2.0.0.alpha you can change either dir or pixel offset with a quick edit menu. To see it just select an instance of the object on the map. I believe it's a more straightforward way to do that.
> 
> <img alt="Screenshot 2022-03-01 at 20 44 27" width="1099" src="https://user-images.githubusercontent.com/12721311/156237663-2171edaa-a266-4f0e-8db0-85c4b6c85cc8.png">


You're correct in that, but it's very far away for me as i can not move it around.

I have a High Res. monitor which means it ends up being far in the bottom right corner.

I think if i could move it around freely it would be better, or a toggle to add back the old right click menu perhaps?

**Comment by SpaiR** [comment]
Fair enough. I'll consider about possible options.

**Comment by Nanu308** [comment]
Thanks, looking forward to see more features and work done on the new SDMM! ^^
