### ISSUE TITLE
Feature Request: Re-bind Keybinds

### ISSUE THREAD

**Issue by Nanu308** [SpaiR/StrongDMM#120]
### Problem to be solved

SDMM Alpha V2.0.0.alpha added in a new selection method, but a lot of us are used to the old method from old SDMM or find the new keybinds unusual.

### Sugest a solution

I think it would be great to have a way to rebind keybinds, such as for search, selecting objects/items, enabling/toggle of filters and changing the active window.

This would let each user decide themselves what works the best for them.

**Comment by SpaiR** [comment]
#119
