### ISSUE TITLE
Bug: StrongDMM closes imediately after launching it

### ISSUE THREAD

**Issue by Conchuckter** [SpaiR/StrongDMM#127]
### Version

v2.1.0.alpha (I just downloaded it from the home page on github)

### What happened?

After extracting the application and launching it, it would imediately close.

### Reproduction

1. Download StrongDMM from repo home page

2. Extract StrongDMM

3. Run StrongDMM

### Relevant log output
[2022.03.13-23.32.35.log](https://github.com/SpaiR/StrongDMM/files/8239440/2022.03.13-23.32.35.log)

**Comment by Conchuckter** [comment]
Lack of logs is because I was unable to launch it in the first place

**Comment by SpaiR** [comment]
Without any logs I can't do anything with your problem... How am I even supposed to understand what has happend?

**Comment by SpaiR** [comment]
Run StrongDMM with cmd, so you'll get an application output to it. Also, I believe, logs still should exist. Go to the app folder described in the README. Otherwise, I can't do anything about the problem described as "something bad happens, help".

**Comment by Conchuckter** [comment]
Sorry bout that, I'll have a look for the logs and run it in the cmd though

**Comment by Conchuckter** [comment]
Oh huh, it worked when I ran it using cmd.
