### ISSUE TITLE
Idea: Instances on turfs that support directionals

### ISSUE THREAD

**Issue by Nickkoranda** [SpaiR/StrongDMM#13]
In order to have clean outlines like this: https://i.imgur.com/PfLEDMW.png you need to change the directional on corner and side floors. 
Currently this is supported in things like cable terminals, but in order to make your instance window filled up you need to edit the dir var on each floor turf, like so: https://i.imgur.com/h3aVmrM.png

**Comment by SpaiR** [comment]
Will be a part of the next release and will look like this
![image](https://user-images.githubusercontent.com/12721311/73299103-9c2f8200-421f-11ea-96d3-9a18cdb5dfe7.png)
Works in the same way as in DM
