### ISSUE TITLE
Feature Request: Open Multiple Maps

### ISSUE THREAD

**Issue by san7890** [SpaiR/StrongDMM#137]
### Problem to be solved

Whenever I want to do stuff like diagnose modular mapping over on /tg/, it's really hard to manage when I have to go back into the maps folder and click a bunch of times to find the exact map I need to load it in.

### Sugest a solution

Have an option to load multiple maps in at once, maybe? It would be nice to Ctrl+Click a bunch and get them all loaded.

**Comment by SpaiR** [comment]
#86 

I've already investigated request like that. It's technically impossible to implement such functionality in the system dialog. Yet I was planning to add it to the "Open Available Maps" panel, when it will be ready.
