### ISSUE TITLE
Feature Request: Legacy keymapping

### ISSUE THREAD

**Issue by PestoVerde322** [SpaiR/StrongDMM#144]
### Problem to be solved
As the title say, due to many many people being still used to the old StrongDMM configurations, including myself, tend to use the old hotkeys (example: holding shift + left click picks the object that you're hovering, but in SDMM2, it will do nothing as instead, that input is now holding S + left click).

### Suggestion

Would be nice to have a "legacy keymapping" mode toggle-able from the settings just because my muscle memory (and likely many other) just gets in the way when using SDMM2.

### Suggest a solution
Add a "legacy keymap" mode with all the old hotkeys, or alternatively, add a way to map hotkeys as you like instead of holding them static.

**Comment by SpaiR** [comment]
#119
