### ISSUE TITLE
non-English characters support?

### ISSUE THREAD

**Issue by Gesugao-san** [SpaiR/StrongDMM#15]
Read more about this please: http://www.byond.com/forum/post/2520672

There is no DDM-analog editors with support non-English characters in WHOLE INTERNET!

Maybe… Someday… I will see this characters as are normal symbols, not something weird… p.. please..

**Comment by SpaiR** [comment]
Java (or Kotlin, it's about the same thing here) supports Unicode out of the box. I'm pretty sure that stuff like variables values and so on should be rendered properly. So I'm not fully understand what kind of support you request from the editor side.

**Comment by Gesugao-san** [comment]
> Java (or Kotlin, it's about the same thing here) supports Unicode out of the box. I'm pretty sure that stuff like variables values and so on should be rendered properly. So I'm not fully understand what kind of support you request from the editor side.

See screenshots from this post please: http://www.byond.com/forum/post/2527860

**Comment by Gesugao-san** [comment]
> Java (or Kotlin, it's about the same thing here) supports Unicode out of the box. I'm pretty sure that stuff like variables values and so on should be rendered properly. So I'm not fully understand what kind of support you request from the editor side.

https://media.discordapp.net/attachments/519252949730459688/653535570341003304/unknown.png?width=528&height=331

**Comment by Gesugao-san** [comment]
Windows 10 x64 and yes, there is only English characters. Original DDM editor from BYOND is normal showed English character, but not non-English.

**Comment by Gesugao-san** [comment]
@SpaiR? Please?...

**Comment by SpaiR** [comment]
То что ты показываешь на скриншоте выглядит для меня как проблема твоей системы. Полагаю, у тебя не хватает каких-то шрифтов или чего-то такого. В любом случае, подобных кейсов мне никто не репортил, да и вижу я нечто подобное впервые. Т.к. редактор написан на фреймворке, который должен, плюс-минус, работать на всех ОС одинаково. Рендер английского текста - тривиальная, в подобном контексте, задача. Учитывая что часть `Type: no type selected`, как и кнопка поиска, рисуются у тебя нормально - все запутывается еще больше. О подобных случаях я в интернете тоже ничего найти не могу, поэтому не думаю что у меня получится твой баг даже воспроизвести. Не говорю уже о том, что у меня просто технически нету возможностей как-то повлиять на то, как отрисовывается шрифт только лишь в менюбаре.

Что касается твоего первоначального реквеста - я все еще не понимаю чего ты просишь. Я видел твои скриншоты в дискорде. Если ты хочешь сказать, что имя в редакторе рисуется плохо, вот не английски `name` в StrongDMM:
![image](https://user-images.githubusercontent.com/12721311/70933946-e7197f80-204d-11ea-9ed0-7ffee67cb4a3.png)

Тоже самое из бьендовского редактора:
![image](https://user-images.githubusercontent.com/12721311/70934108-3790dd00-204e-11ea-8d8a-dc41fd7a7d39.png)

За исключением сломанной буквы `я` - все ок, а не как на скриншоте у тебя. (У меня обычная Win10 с русским и анлийским языками.)

Если ты делал скриншоты из 513 - это баги бета версии, их нужно репортить на форуме бьенда.

Если русский текст помещенный на карте по итогу плохо рендерится в игре - на это я тоже повлиять не могу, это проблемы все того же бьенда. Т.к. в 513 он должен перейти на поддержку юникода, то они пофиксятся сами собой, но до стабилизации версии остается только ждать и, как я уже сказал, сообщать о багах на форуме, где разрботчики бьенда их увидят.

**Comment by Gesugao-san** [comment]
> проблема твоей системы

Уверен, что так. Потому что использовал экспериментальный патчинг и шрифты отсюда:
https://youtu.be/cyR3S-_Kblk
Причём это только на домашнем компьютере.
> не хватает каких-то шрифтов

Я пробовал и восстанавливать, и язык по умолчанию, чего только не пробовал. Думаю, пора переустанавливать шиндоус. Не только из-за этого, давно уже не переустанавливал. Причём здесь старая сборка стоит OVGorskiy. Предпочитаю сборник версий от SmokieBlahBlah, но на данный момент уже популярны сборники от Eagle123.
> О подобных случаях я в интернете

Я пробовал искать. Не спрашивай, как, но нашёл очень похожее по запросу «scrambled text»:
https://www.google.ru/search?tbm=isch&q=scrambled+text#imgrc=rkkBrMko3sK5DM:

**Comment by SpaiR** [comment]
> Я пробовал искать. Не спрашивай, как, но нашёл очень похожее по запросу «scrambled text»

😑 Это так не работает, если что.

Я говорил про поиски "подобные случаи" в контексте фреймворка и языка на котором написан редактор, а не в отрыве от всего в целом, и твоей проблемы в частности, как это сделал ты.

**Comment by Gesugao-san** [comment]
Ясно.
Тогда пару вопросов не по теме: как ты смотришь на то, чтобы я попробовал добавить возможность выбора языка интерфейса (или ты, по каким-либо причина), и предложить единственному разработчику бульона — Люмоксу — улучшить стандартный редактор кодом из этого дистрибутива или из аналогов?

**Comment by SpaiR** [comment]
> как ты смотришь на то, чтобы я попробовал добавить возможность выбора языка интерфейса

Сейчас это не имеет смысла, т.к. я переписываю редактор целиком в параллельной ветке. Поддержка же нескольких языков суть скорее жир, чем необходимость. В том плане, что интерфейс не на столько сложный и насыщенный в плане текста, чтобы требовал локализации. То что, например, у тебя проблемы с текстом, как уже выяснилось, проблемы локальные. И я бы порекомендовал с ними разобраться, т.к. мой редактор не что-то уникальное. Всплыли проблемы в нем, могут всплыть запросто и в других приложениях.

> улучшить стандартный редактор кодом из этого дистрибутива или из аналогов

Это невозможно. Как минимум из-за того, что этот редактор написан на одном языке, DM - на другом. Тоже касается аналогов. Переносы не работают как "взять папку из одной кодбазы и перетащить в другую". Максимум что можно сделать - делать предложения по улучшению редактора на форуме бьенда, но это может сделать любой.

**Comment by Gesugao-san** [comment]
> Сейчас это не имеет смысла

А в переписанной версии это тоже не будет считаться необходимостью? Ждать, или, если как-то смогу, самостоятельно попробовать, стоит?
> делать предложения по улучшению

Могу его засыпать предложениями, но стоит ли? Он один, а задач много. Особенно проблем, которые решает он один.

**Comment by SpaiR** [comment]
> Ждать, или, если как-то смогу, самостоятельно попробовать, стоит?

Если как-то сможешь, то можешь попытаться. Но я ничего не общею.

> Могу его засыпать предложениями, но стоит ли? Он один, а задач много. Особенно проблем, которые решает он один.

Я не понимаю почему ты спрашиваешь об этом меня. Делай как считаешь нужным.

**Comment by Gesugao-san** [comment]
>  можешь попытаться

Спасибо, что не против. Уже многократно мучался, пытаясь установить Gradle…
> Делай, как считаешь нужным.

Так и говори: это не моё дело и мне всё равно.
Хорошо, попробую.
