### ISSUE TITLE
Bug: dmmdata/parse.go doesn't handle Y coordinates properly

### ISSUE THREAD

**Issue by d0sboots** [SpaiR/StrongDMM#151]
### Version

v2.5.4.alpha

### What happened?

This map, which works fine in-game, is totally messed up in the editor. (It has a big vertical stripe through the supermatter engine and atmos.)

I made the map by tweaking Meta and fiddling with the chunks. You'll immediately see the cause when you look at how the chunks are broken up, and your assumptions about what that means don't match the game's.

I wasn't doing this just to try and break things; the game loads everything sequentially, so if you want certain scrubbers to appear in a certain order in the SM air alarm (for instance), this is the only way I know of to accomplish it.

### Reproduction

1. Run StrongDMM
2. Load the attached map [FastStart.zip](https://github.com/SpaiR/StrongDMM/files/8786863/FastStart.zip)

### Relevant log output

```bash
None, there's nothing in the logs to indicate (for instance) that it's trying to put tiles off the map, or that tiles were left empty.
```

**Comment by SpaiR** [comment]
Please, give the link to the codebase you're using the map with.

**Comment by d0sboots** [comment]
My bad. It's <https://github.com/BeeStation/BeeStation-Hornet>.

The issue is apparent enough that you can *probably* load the map with tgstation or most forks and it will still be apparent, despite all the missing types.

**Comment by SpaiR** [comment]
> I wasn't doing this just to try and break things

And you've, basically, broke things... The blocks you've pasted in the map file a totally invalid. They are violating .dmm syntax. And I don't see any reason to support map files filled with gibberish stuff. The fact that it's loaded in game is mostly a merit of the custom map loader which is used by all SS13 codebases.

<img width="144" alt="image" src="https://user-images.githubusercontent.com/12721311/170814384-4ef3889f-6f3d-4f89-ab90-3deccc03fc51.png">

**Comment by d0sboots** [comment]
Of course it's not DMM syntax, because it's TGM. If there's any actual standard for TGM aside from the map loader code in the SS13 codebase, I haven't been able to find it.

And yes I know that these blocks won't be preserved by any map editor when the map is saved, nor am I asking for that, but _that's not the point_. I can (and have) made a file like this which loads perfectly fine in StrongDMM, but is completely messed up in-game, because you're doing your y-axis math wrong. That's the point.

**Comment by d0sboots** [comment]
Will you accept a patch if I fix it for you? I know Go, but I don't have the full toolchain and all that jazz set up here to build the binaries.

**Comment by SpaiR** [comment]
> DMM syntax, because it's TGM

TGM is not a **syntax**, TGM is a **format**. You can put map data in different formats, but the point is to have a proper syntax which can be read by BYOND.

> Will you accept a patch if I fix it for you?

You don't need to ask, everyone can contribute anything 😄 If the patch will be fine in general, I see no problem to accept it.

**Comment by d0sboots** [comment]
> TGM is not a **syntax**, TGM is a **format**. You can put map data in different formats, but the point is to have a proper syntax which can be read by BYOND.

You're right of course about the semantic distinction. TGM and (what's called) DMM are both formats that share the same syntax, and what I did with my map was another (more radical) variation with the same syntax.

You got me thinking though, so I tested out how DreamMaker itself handles this. The answer was surprising to me: It does the same thing as SDMM, reading vertical positions with "inverted" coordinates and then flipping them after. You can see this in the small test project I'm attaching.

[map_test.zip](https://github.com/SpaiR/StrongDMM/files/8795267/map_test.zip)

Based on that, there's definitely no action to be taken here, although I'm still working on a PR to add tests to `parse.go`. I'll also see about making changes to SS13's parsing to match BYOND, although we'll see how that goes...
