### ISSUE TITLE
Feature Request: Add StrongDMM.exe to Windows PATH

### ISSUE THREAD

**Issue by san7890** [SpaiR/StrongDMM#162]
### Problem to be solved

From the project's ReadMe:

![image](https://user-images.githubusercontent.com/34697715/187773532-840f3b1c-b73e-4e0a-a867-2e420a715e75.png)

This feature does work nicely _if_ you CD to the folder in which you have the portable StrongDMM.exe saved to. Otherwise, it's not recognized by Windows as a proper `cmdlet, function, script file, or operable program`.

![image](https://user-images.githubusercontent.com/34697715/187774843-366bde0b-823f-4f06-a620-85494af4ec65.png)

### Suggest a solution

Is it possible to add StrongDMM.exe to the Windows PATH such that Windows does indeed recognize it as a proper operable that can accept the two arguments so you don't have to CD like this? That would be very well appreciated.

**Comment by SpaiR** [comment]
The problem here is that executable is fully self-containable and doesn't install itself to a specific folder. Thus it's impossible to give any guaranties, that the path to the exe won't be changed. (For example, by the user himself.) You can add strongdmm to your system PATH manually though.
