### ISSUE TITLE
Bug: Everything Is White

### ISSUE THREAD

**Issue by BetaCentari** [SpaiR/StrongDMM#167]
### Version

2.6.2.Alpha

### What happened?

When I load up my environment and a map, the map is almost entirely white with the exception of some little bits and strings of color here and there when peeling back layers.

I've tried clearing my BYOND Cache and switching versions. 1.9.1. seems to work just fine but the more recent versions just don't. I'm currently on BYOND Version 514.1583, I've recompiled my .dme many times and tried pulling my hair out. Nothing seems to work.  

![Capture](https://user-images.githubusercontent.com/17231562/204631036-af009b84-1694-43aa-972c-16951e321816.PNG)

### Reproduction

1. Run StrongDMM
2. Open Environement 
3. Open Map 
4. Gaze Upon It

### Relevant log output
[2022.11.29-12.34.12.log](https://github.com/SpaiR/StrongDMM/files/10116736/2022.11.29-12.34.12.log)

**Comment by Bm0n** [comment]
If I am not mistaken this seems to be the same issue as in issue https://github.com/SpaiR/StrongDMM/issues/161

**Comment by BetaCentari** [comment]
> If I am not mistaken this seems to be the same issue as in #161

Seems to the case, thanks for pointing that out for me. I'll give the solution a try.

**Comment by SpaiR** [comment]
#161
