### ISSUE TITLE
Bug: Blank map

### ISSUE THREAD

**Issue by Danefalt** [SpaiR/StrongDMM#168]
### Version

2.6.2 alpha

### What happened?

One day, the map im working of just became blank. Literally blank. No turfs, no objects, no areas, no mobs, X:0 Y:0 Z:0. There was literally nothing. Just a blank dmm file. 
The map isnt corrupted, i still can open it with DM or SDMM 1.1.0, and it'll be shown as it should be. The file also has the whole data about map.
But in SDMM 2.6.2 its just impossible to open it without all work loss. And the hardest part - this stuff is going only with exactly that map. Every other maps opens without any trouble.

SDMM 2.6.2:
![StrongDMM_MdBCvLXGbd](https://user-images.githubusercontent.com/64663936/209474213-b1709f51-0ba5-4e42-9a55-9094f8099782.png)

SDMM 1.1.0:
![StrongDMM_zskRJZWFKG](https://user-images.githubusercontent.com/64663936/209479110-64226e6b-6332-472f-8c61-d20d8555620a.png)

DM:
![dreammaker_1VhmzQllGR](https://user-images.githubusercontent.com/64663936/209474246-5289b888-c86a-4d9a-8446-1e902005b127.png)

(I have some problems with sumbiting issue with the logs (they're so huge), so i'll just drop them here)
[2022.12.23-21.27.06.log](https://github.com/SpaiR/StrongDMM/files/10300273/2022.12.23-21.27.06.log)

Additional:
Map sizes - 310x310x1
Map format - TGM

### Reproduction

1. Run StrongDMM
2. Open map
3. ???
4. Blank map

**Comment by SpaiR** [comment]
#161 161
