### ISSUE TITLE
Map Corrupts after saving, unable to edit further

### ISSUE THREAD

**Issue by ghost** [SpaiR/StrongDMM#17]
Editing a lavaland ruin for TG, after I saved it then compiled in dreammaker, it deleted a few tiles completely and replaced some other tiles with sinks as shown here:
![image](https://user-images.githubusercontent.com/48036854/71423792-b642d700-2659-11ea-8db0-f58305f25e9b.png)

Trying to save the file after this occurs causes StrongDMM to freeze completely and does not allow any other action to occur. I had to forcequit the application in task manager. Saving does not succeed.

Trying to edit the map in dreammaker afterwards gives this error
![image](https://user-images.githubusercontent.com/48036854/71423866-57ca2880-265a-11ea-97e9-32608e0f964c.png)

**Comment by CAPTTLasky** [comment]
I was just able to replicate this issue when trying to recreate the map file, this time opening without having compiled in dreammaker.
![image](https://user-images.githubusercontent.com/48036854/71424451-99110700-265f-11ea-9491-67b38e7873bd.png)

**Comment by CAPTTLasky** [comment]
The error seems to be happening in the same spot regardless of what version. I just pulled up my backup version and the issues were in the same spots
![image](https://user-images.githubusercontent.com/48036854/71424473-da091b80-265f-11ea-98c4-ca13af1da8b0.png)

**Comment by CAPTTLasky** [comment]
It seems to have something to do with objects, as loading the backup I had with only turf changes did not result in the same issue.

**Comment by CAPTTLasky** [comment]
Just saw that this issue may go deeper than just the map file. I had to revert to a version without any StrongDMM map changes in order to use dreammaker again. It wasn't able to read any map files.
