### ISSUE TITLE
Scaling issue on high resolution

### ISSUE THREAD

**Issue by silicons** [SpaiR/StrongDMM#18]
I have a 4k screen, my desktop's usually at 125-150% scaling
Unfortunately, this doesn't seem to apply to strongDMM.
![image](https://user-images.githubusercontent.com/2003111/79085898-133cc880-7cef-11ea-8057-83e2f54c7481.png)

**Comment by SpaiR** [comment]
Yes, I know about this problem. Unfortunately UI toolkit I'm using doesn't provide automatic HIDPI support out of the box. So it should handled manually. I have plans for this in future.
