### ISSUE TITLE
Feature Request: format var-edited associative lists to match fastdmm2

### ISSUE THREAD

**Issue by ToasterBiome** [SpaiR/StrongDMM#187]
### Problem to be solved

When a codebase is split between StrongDMM and fastdmm2, they're almost completely 1:1 except for var-edited associative lists. Fastdmm2 adds spaces to pad the list, which I believe to be superior as it's more readable.

When a PR is made where the last version of the map was edited in the other version, you get a line change for every var-edited thing, which is not very good when a 1 tile change is automatically a 40~ line change for no reason.

See above: Fastdmm2
Below: Strongdmm

![image](https://user-images.githubusercontent.com/5091394/235044777-99382d68-1ac9-4cab-b580-bbfc0a7af295.png)

### Sugest a solution

Pad strongdmm associate lists with the spaces.

**Comment by ToasterBiome** [comment]
Allegedly the way that fastdmm2 does it is also the way that dreammaker itself saves.

**Comment by monster860** [comment]
This is the way Dream Maker saves.

Here's what it looks like:

![image](https://user-images.githubusercontent.com/3681297/235047460-daa7a7d1-b56d-410f-a927-06214b2f1f08.png)

If I try to edit it to not have the spaces it just puts the spaces back.
