### ISSUE TITLE
Bug: Saving a map causes double whitespaces in object's vars

### ISSUE THREAD

**Issue by Furrior** [SpaiR/StrongDMM#209]
### Version

2.7.3 alpha

### What happened?

When you save a map that has objects with some vars with whitespaces in them, whittespaces are doubled.
More on coderbus discord: https://discord.com/channels/484170914754330625/484282183737933835/1128557345723654164

### Reproduction

1. Run StrongDMM
2. Open a map that has objects with map defined vars containing a whitespace
3. Do anything
4. Save the map
5. Whitespaces are doubled

**Comment by Furrior** [comment]
![изображение](https://github.com/SpaiR/StrongDMM/assets/68264134/a33354fd-a074-4c5f-86c8-b382bc9a11fe)

**Comment by SpaiR** [comment]
99% that #195 is the reason. @itsmeow can you look for the problem?
