### ISSUE TITLE
Feature Request: Edit Instance similar to DM

### ISSUE THREAD

**Issue by KathrinBailey** [SpaiR/StrongDMM#21]
Once I tried the new StrongDMM (it's awesome and saves a ton of time) I told Cinder that you can't actually delete instances, do you kind of have a big giant list. You can't edit instances either.
It'd be really awesome if we had the ability to edit instances (and delete them of course).

~~Would it also be possible to get something akin to mapdiffbot and render an image of the entire map and put it on your clipboard, or save it as a .png or something? It'd be helpful to be able to get high resolution images of large parts of the map.~~

**Comment by SpaiR** [comment]
To simplify progress tracking, I've decoupled the second part of the issue into a separate #31

**Comment by SamuelRowe** [comment]
In my opinion, this would make the StrongDMM map editor superior to every other DM-based map editor out there (Although it definitely already is)
