### ISSUE TITLE
Bug: windows 11 wont work

### ISSUE THREAD

**Issue by Blu48888** [SpaiR/StrongDMM#238]
### Version

v2.8.1.alpha

### What happened?

I can open the app and everything but the moment i open anything and move my mouse or press a button it wont do anything and from what i understand its cause im using windows 11 but i honestly cant revert to windows 10 man i dont know what the hell to do

### Reproduction

1. use windows 11 (sad)
2. run strongdmm
3. open a DME or map
4. do anything
5. crash

**Comment by vilereaver41** [comment]
Same ;/

**Comment by Qumefox** [comment]
Do you have an AMD GPU by any chance?

**Comment by SpaiR** [comment]
duplicate of #161
