### ISSUE TITLE
Bug: Wide missed icon placeholder

### ISSUE THREAD

**Issue by Aylong220** [SpaiR/StrongDMM#242]
### Version

2.9.0

### What happened?

Wide placeholder for the missing icon
![image](https://github.com/SpaiR/StrongDMM/assets/69762909/9caa0692-dcde-44a2-84b3-3491d703f485)

### Reproduction

1. Run StrongDMM
2. Open Map
3. Find (or create) object with incorrect icon_state.
4. ???

**Comment by out-of-phaze** [comment]
https://github.com/SpaiR/StrongDMM/blob/53b641a436e7f65bdad3e534ee04d90646bd347c/internal/dmapi/dmicon/editor.go#L18
This change seems unintentional? The texture/icon is still 32x32, the image is just 64x32. That should be handled by `Cols` being 2 and `Rows` being 1, giving a total dimension of 64x32.
