### ISSUE TITLE
New logo proposal

### ISSUE THREAD

**Issue by clement-or** [SpaiR/StrongDMM#26]
It has occured to me that the current logo isn't really suited for an app icon. I'm a graphic designer and I use Strong DMM. Here is a quick proposal for a new logo. If you're willing to change the logo, I can take any criticism on this proposal and I can create any number of logos till it's good.

If you want to keep the current one then you can close this issue.
![strongDMM](https://user-images.githubusercontent.com/29918611/80116395-346ea600-8586-11ea-9e37-b76ea970db35.png)

**Comment by SpaiR** [comment]
Great work! The icon looks good, I see the idea you've put in it and I like the way it fits to the app itself.  The current one is just a placeholder, so I'll definelty love to use yours.

The only thing is that I would like to point out your authorship. Could you please provide the way I can mention you in Credits/Changelog?

**Comment by clement-or** [comment]
Hi,

You can credit me as **Clément "Topy"** or just **Topy** as you'd like. I can and will try to make better versions of this icon, I'm not entirely satisfied as it is.
Thanks for you answer !
