### ISSUE TITLE
SpacemanDMM parser is out of date

### ISSUE THREAD

**Issue by ZeWaka** [SpaiR/StrongDMM#289]
### Version

v2.11.0.alpha

### What happened?

The current version of the parse will choke on features not present in the outdated version, like `#if fexists('xyz')`

If it could be updated to the latest version, that'd be great. There's no current suite release out, but I've requested one: https://github.com/SpaceManiac/SpacemanDMM/issues/392

### Reproduction

1. Run StrongDMM
2. Open codebase that relies on newer spacemandmm parsing (like Goonstation's secret submodule)
3. fail

**Comment by ZeWaka** [comment]
Here is the new suite release: https://github.com/SpaceManiac/SpacemanDMM/releases/tag/suite-1.9

**Comment by SpaiR** [comment]
fixed in #294
