### ISSUE TITLE
sddmlauncher seems to append the version string instead of replacing

### ISSUE THREAD

**Issue by DamianX** [SpaiR/StrongDMM#29]
![image](https://user-images.githubusercontent.com/6307265/80715032-11984080-8af6-11ea-9ede-8027aa725f78.png)

Each time I run sddmlauncher it adds one more. I'm using latest sddmlauncher from the 1.1.0 release.

**Comment by SpaiR** [comment]
Yeah, it's a known problem. The next release of the editor will be accompanied by the release of the launcher with the corresponding fix. For now the workaround is to delete the `version` file under the `home user dir/.strongdmm` folder.
