### ISSUE TITLE
Bug: SDMM layer wonkiness

### ISSUE THREAD

**Issue by Jolly-66** [SpaiR/StrongDMM#292]
### Version

2.11

### What happened?

Using SDMM on /tg/ code with https://github.com/tgstation/tgstation/pull/84350 merged causes rendering issues when it comes to layers.

(I was also directed to post this here as a bug, I'm not a coderman so I don't understand whats going on)

![image](https://github.com/SpaiR/StrongDMM/assets/70232195/b0bb831c-261a-425f-9383-e2c79d2aafa2)

### Reproduction

1. Use SDMM on /tg/ code with aforementioned PR
2. Open any map
3. See images below

All the layers are on, but primarily turfs are visible. Areas are only visible on closed turfs.
![image](https://github.com/SpaiR/StrongDMM/assets/70232195/b5771f99-92dd-4616-832b-2fe373311279)

Hiding turfs causes anything rendered underneath it to appear.
![image](https://github.com/SpaiR/StrongDMM/assets/70232195/03383858-9f30-4a22-9342-3d66d4ed996d)

**Comment by LemonInTheDark** [comment]
We're using `TOPDOWN_LAYER` now (raw value of 10000). The fact that changing every object on the floor plane to use this as an offset broke layering implies that strongdmm does not consider the `plane` variable at all when rendering.

I can handle this with compile time fuckery on our side but ideally the renderer would support planes as superlayers.

**Comment by LemonInTheDark** [comment]
See also https://github.com/tgstation/tgstation/pull/84659
