### ISSUE TITLE
Add way to mass delete items in selection?

### ISSUE THREAD

**Issue by steamp0rt** [SpaiR/StrongDMM#3]
Like doing a selection then Ctrl+H in DreamMaker.

**Comment by ZeWaka** [comment]
I feel like selection + Delete/Backspace would be more intuitive.

**Comment by SpaiR** [comment]
Are you speaking about mass deletion of **all** items? If you are, such operation exists with RMB in selection + 'Delete' option in popup menu. (yeah, shortcut is still required) Ctrl+H seems more about replacing specific items and when there is no type to replace with, specific items will be just removed.

**Comment by steamp0rt** [comment]
Yeah. Like when I was fixing the Hippie map for the smart wiring, I had to, in DreamMaker, remove all `/obj/structure/cable` from a selection
