### ISSUE TITLE
Bug: #warn stops SDMM from open map.

### ISSUE THREAD

**Issue by AlexMorgan3817** [SpaiR/StrongDMM#326]
### Version

2.14.0

### What happened?

A bug happened!
![image](https://github.com/user-attachments/assets/c02b0d9d-b59f-4589-91e0-a07e68cf1a07)
Warning should not be considered as errors.

### Reproduction

1. Run StrongDMM
2. It updates to 2.14.0
3. Your
```dm
#ifdef DEBUG
  #warn "BUILD IS RUNNING ON DEBUG MODE"
#endif
```
is preventing you from mapping

### Relevant log output

```bash
2024-11-20 17:58:22 DBG sdmm/internal/app/project.go:147 > unable to open environment by path:roguetown.dme
parser error: compilation errors
  code/testing.dm - [7:2] | #warn compiling in FASTLOAD mode.
```

**Comment by AlexMorgan3817** [comment]
@SpaiR, what if add option Run Anyway

**Comment by SpaiR** [comment]
> @SpaiR, what if add option `Run Anyway`

I believe this can be fixed [here](https://github.com/SpaiR/StrongDMM/blob/b2a84e565778cd64bffc48a2589e5f495009cbaf/third_party/sdmmparser/src/environment.rs#L56) by adjusting the filtering to only include `ERROR` severity. I just didn't account for the `WARN` case.

**Comment by AlexMorgan3817** [comment]
> > @SpaiR, what if add option `Run Anyway`
> 
> I believe this can be fixed [here](https://github.com/SpaiR/StrongDMM/blob/b2a84e565778cd64bffc48a2589e5f495009cbaf/third_party/sdmmparser/src/environment.rs#L56) by adjusting the filtering to only include `ERROR` severity. I just didn't account for the `WARN` case.

The problem is not only with warn directive, but with other not severe issues, like define redefinition, backslash in comments. I fixed them, but still have 88 warning that were not mentioned in SDMM's popup about errors

**Comment by SpaiR** [comment]
`Warn` severity doesn't mean specifically `#warn` directive. It's about all problems which don't affect final project parsing result. Anyway, I've already released fixed version, try to update the editor.

**Comment by AlexMorgan3817** [comment]
> `Warn` severity doesn't mean specifically `#warn` directive. It's about all problems which don't affect final project parsing result. Anyway, I've already released fixed version, try to update the editor. 

Thank you very much!
