### ISSUE TITLE
Idea: Readd synchronize maps option

### ISSUE THREAD

**Issue by CrimsonShrike** [SpaiR/StrongDMM#38]
An older version of StrongDMM seemed to have an option to synchronize coordinates when switching from one map to another which was very useful for Multiz mapping. Would it be possible to bring that feature back?

Reference:

![image](https://user-images.githubusercontent.com/29737699/82377465-97374e00-9a1b-11ea-80fe-79094326f812.png)

**Comment by SpaiR** [comment]
Yeap, it is possible. I've just didn't get enough feedback about that feature, thus I was thinking that it's useless. If it's really useful, then I can readd it.
