### ISSUE TITLE
modified file asterisk does not ever get removed

### ISSUE THREAD

**Issue by actioninja** [SpaiR/StrongDMM#4]
v 0.0.2
how to reproduce:
open file
modify file so that it gets an asterisk to indicate it's modified
save
see that asterisk is still there despite saving

**Comment by steamp0rt** [comment]
very annoying issue

**Comment by SpaiR** [comment]
Thank you for your report! I will get it very soon.

**Comment by SpaiR** [comment]
Will be part of `v0.0.3` release.
