### ISSUE TITLE
Feature Request: add "Overlay Ruler" and/or X/Y lock. 

### ISSUE THREAD

**Issue by Albens** [SpaiR/StrongDMM#41]
On BYOND DMM, the ability to move along a specific X or Y axis can be done using the Mouse Wheel, (+Control) to pan, while not moving your mouse. 

This can be used for moving selections on a single axis, and can be helpful when shifting objects about.

As this keybind is not retained, the ability to shift things along one Axis (Ie X:025 to X:050) while retaining the same Axis (Ie Y:025) is made harder. 

Adding in an Overlay Ruler, that displays a count of tiles under it, and has a visual Overlay that can aid in placement/moving of Selection Objects is desired. 

Otherwise, the ability to Pan along a specific Axis (ie Byond DMM Control Scheme Parity or otherwise) while moving a selection is desired.

**Comment by SpaiR** [comment]
Moving along a specific axis is supported with "arrow keys movement" (from v1.3.0). I'll add a speed modifier, so with pressed "shift" button camera will move faster. Other options for X/Y-locking seems redundant for me.
