### ISSUE TITLE
Feature Request: Reset to Default Option/Hotkey for Specific Variables in Edit Variables Window. 

### ISSUE THREAD

**Issue by Albens** [SpaiR/StrongDMM#45]
Add a button or Hotkey to allow a Selected, highlighted, or Actively Editing Variable to be reset to default from within Edit Variables Window. 

Suggested Hotkey: Ctrl+Shift+ Double Click a Variable to Reset it to Default instead of edit it.

**Comment by SpaiR** [comment]
I'm not sure about using of the hotkey for that. Without a proper guide about application shortcuts it will be unobviously for usage. Maybe adding a button near to edit field...
