### ISSUE TITLE
Idea: hollow rectangle/circle tool

### ISSUE THREAD

**Issue by ghost** [SpaiR/StrongDMM#5]
exactly what the title says. make a hollow shape of whatever you have selected

**Comment by SpaiR** [comment]
I'm not quiet sure that can understand you idea correct. Could you please provide more details of how it should look like and how it could be used. Maybe cases where such tool could be useful.

**Comment by steamp0rt** [comment]
like the tool in an image editor

github won't let me embed mp4s: https://img.steamport.xyz/oSvetaskpq.mp4

**Comment by SpaiR** [comment]
I see. But isn't current "Pick" select mode is a sort of "rectangle" tool?

**Comment by steamp0rt** [comment]
no? you can't make a rectangle of objects with it.

**Comment by SpaiR** [comment]
Ok, you've didn't said that the point of the tool is to fill an area with objects. So what about "Fill" select mode than?
![tool](https://user-images.githubusercontent.com/12721311/60154552-5bd2d600-97f0-11e9-9aac-2b09674f2514.gif)
Do we really need something, that will work with rectangle area specifically if we already have this, which provides ability to make square forms from itself? I was thinking about adding some additional info about selection mode to the status row (near the coordinats). With this data user will see how many tiles he has selected and 'width x height' sizes of selected area. Such info will simplify the process of making rectangle shapes.

**Comment by steamp0rt** [comment]
I was just thinking this would be useful for making rooms
