### ISSUE TITLE
Request: Find and Replace in Selection

### ISSUE THREAD

**Issue by GreyTide2108** [SpaiR/StrongDMM#51]
Dream Maker has an option in it's right click menus to search for things in a selected area and replace them with another object or delete them by leaving the replace box blank. This is immensely useful for deleting items of the same type on mass, even if it is achievable by Ctrl+Shift+Clicking them individually.

![KUTiRe7tiU](https://user-images.githubusercontent.com/65935938/82859484-d7e40b00-9ee4-11ea-94e7-b8d381024c8e.gif)

**Comment by SpaiR** [comment]
StrongDMM already has this feature. Search square is available in the Instance Locator panel. As well as the button to take a currently selected area.

![f](https://user-images.githubusercontent.com/12721311/82879187-4789e280-9f45-11ea-89f1-611c27f9ffcc.gif)
