### ISSUE TITLE
При запуске Bat файла выдает ошибку: "Не удается найти ".\runtime\bin\javaw.exe"Проверьте, правильно ли указано имя файла и повторите попытку."

### ISSUE THREAD

**Issue by VelonacepsCalyxEggs** [SpaiR/StrongDMM#55]
![Screenshot_18](https://user-images.githubusercontent.com/48419312/85863018-32fe6b80-b7cb-11ea-8750-f9af9dc57d13.png)
\
Недавно переустановил винду.
При запуске Bat файла от им.Администратора  открывался CMD и происходила ошибка выше. При запуске файла без им. Адиминистратора, открывался CMD и закрывался.
![image](https://user-images.githubusercontent.com/48419312/85863526-f2532200-b7cb-11ea-86a2-c527bef69d6e.png)

 При запуске через лаунчер, после загрузки файлов он проверял наличие обновлений, писал что открывает StrongDmm, но CMD просто закрывался и ничего не происходило.
![image](https://user-images.githubusercontent.com/48419312/85863738-3fcf8f00-b7cc-11ea-91a1-912fcce81941.png)

**Comment by VelonacepsCalyxEggs** [comment]
![image](https://user-images.githubusercontent.com/48419312/85863919-7c9b8600-b7cc-11ea-9e13-6b1de16546aa.png)
Сам файл кстати на месте

**Comment by SpaiR** [comment]
Какое у тебя имя пользователя?

**Comment by VelonacepsCalyxEggs** [comment]
> Какое у тебя имя пользователя? В нем есть русские символы или нет?

Да, имеются.

**Comment by SpaiR** [comment]
В этом и проблема. Путь должен содержать лишь латинские символы (имя пользователя должно быть на английском). Чтобы убедиться можешь скачать архив напрямую https://github.com/SpaiR/StrongDMM/releases/download/v1.5.0/strongdmm-windows.zip и распаковать где-то, где нету имени пользователя (другой диск или сразу под C:\. Как попробуешь - отпишись тут, пожалуйста, чтобы я понимал, что у тебя именно эта проблема.

**Comment by VelonacepsCalyxEggs** [comment]
> В этом и проблема. Путь должен содержать лишь латинские символы (имя пользователя должно быть на английском). Чтобы убедиться можешь скачать архив напрямую https://github.com/SpaiR/StrongDMM/releases/download/v1.5.0/strongdmm-windows.zip и распаковать где-то, где нету имени пользователя (другой диск или сразу под C:. Как попробуешь - отпишись тут, пожалуйста, чтобы я понимал, что у тебя именно эта проблема.

![image](https://user-images.githubusercontent.com/48419312/85866687-73acb380-b7d0-11ea-8301-953a74a1ee70.png)
Засунул под диск, таже проблема :\

**Comment by SpaiR** [comment]
Хм. В таком случае это другой баг. Проблема в том, что у некоторых рантайм Java, который упакован в архив и находится целиком в папке runtime, по каким-то причинам не запускается. В чем дело я не знаю, поэтому даже варианта решения особо предложить не могу. 

В принципе, ты можешь попробовать поиграться с этим сам, попробовав запустить с рантаймом из этой ссылки https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10.2/OpenJDK11U-jdk_x64_windows_hotspot_11.0.7_10.zip (в архиве поставляется 32-битная версия, а по ссылке 64). Как-то еще помочь с этим не могу, т.к. проблема на стороне пользователя. Если получится найти решению - буду рад услышать и внедрить его в основное приложение.

**Comment by VelonacepsCalyxEggs** [comment]
> Хм. В таком случае это другой баг. Проблема в том, что у некоторых рантайм Java, который упакован в архив и находится целиком в папке runtime, по каким-то причинам не запускается. В чем дело я не знаю, поэтому даже варианта решения особо предложить не могу.
> 
> В принципе, ты можешь попробовать поиграться с этим сам, попробовав запустить с рантаймом из этой ссылки https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10.2/OpenJDK11U-jdk_x64_windows_hotspot_11.0.7_10.zip (в архиве поставляется 32-битная версия, а по ссылке 64). Как-то еще помочь с этим не могу, т.к. проблема на стороне пользователя. Если получится найти решению - буду рад услышать и внедрить его в основное приложение.
Я ввел полный путь к файлу javaw.exe и мне на этот раз выдало эту ошибку
![image](https://user-images.githubusercontent.com/48419312/85890113-68b84a00-b7f5-11ea-8345-49a16e65822c.png)
