### ISSUE TITLE
Bug: multi-Z screenshots are broken

### ISSUE THREAD

**Issue by uomo91** [SpaiR/StrongDMM#56]
A bit hard to explain, but properly exporting multi-z screenshots seems to requiring restarting the editor to be able to do it.

**Comment by SpaiR** [comment]
You need to give more info about that. I've tested screenshots on Eris maps, everything is ok. Could you take a gif or something that will show the issue?

**Comment by uomo91** [comment]
I'll try to screenshot or at least better explain the process soon.

**Comment by uomo91** [comment]
Well, I can verify this is 100% working now. Strange.
Maybe something in a prior update inadvertently fixed it?

Anyway, feel free to close. Thanks.

**Comment by SpaiR** [comment]
I did nothing :confused:
