### ISSUE TITLE
Bug: Windows SDMM Launcher freezes when clicked.

### ISSUE THREAD

**Issue by uomo91** [SpaiR/StrongDMM#57]
Any time I click on the text portion of the cmd prompt window for SDMM Launcher, it freezes.
Especially likely to happen during updates, but it can happen just during normal launch as well.

**Comment by uomo91** [comment]
Pressing enter seems to unfreeze it.

**Comment by SpaiR** [comment]
It's a default Windows console behavior. After the click it expects a user input.
Just don't click into it and let it do its job.
