### ISSUE TITLE
Feature Request: Reiterating "find-replace" functionality request.

### ISSUE THREAD

**Issue by uomo91** [SpaiR/StrongDMM#58]
This was brought up here: https://github.com/SpaiR/StrongDMM/issues/51

You stated StrongDMM already has this, however, it doesn't seem to.
It does indeed have a mass search option, but not mass (or semi-automated) replace something with something else option. Would it be possible to implement this down the road?

**Comment by SpaiR** [comment]
Has you try to hover your mouse over the help mark? It states an instruction how to do a replacement. -_-
I may consider to change a design to make it more obvious, if I'll have ideas about that. 

![image](https://user-images.githubusercontent.com/12721311/86220910-e6c97780-bb8c-11ea-9aaf-893f0ad398e6.png)

**Comment by uomo91** [comment]
Ah, my mistake.
Would it be possible to add the functionality to replace things with complete instances instead of just base types? Is there already some way to replace things with varedited instances?

**Comment by SpaiR** [comment]
> Is there already some way to replace things with varedited instances?

No, it is not. I'll probably add it in the future.

**Comment by uomo91** [comment]
OK, cool. Thanks for your time.
