### ISSUE TITLE
[Bug] Endless environment loading

### ISSUE THREAD

**Issue by Delnth** [SpaiR/StrongDMM#63]
**Tested with**:

- Windows 10 Home
- Administrator mode
- StrongDMM Launcher
- StrongDMM Zip folder
- Latest version (v1.7.1 - 2020/07/13)
- /tg/station based codebases (including /tg/station itself)
- baystation12 based codebases

**Additionally**:

- There is no crash, application runs smoothly and closes itself without any delay when clicking the red cross
- No crash report, error log or prompt that may indicate a problem
- Loading any codebase seem to work, however they never finish loading
- The object tree is not generated, be it after ten, twenty or thirty minutes (waiting more then 2-3 minutes is already an issue in itself)

---

I haven't used StrongDMM in a very long time, it used to work fine before (around a year ago). I'd be very grateful for a bit of assistance, I'm curious about the new features and looking forward to test them out for a project.

**Comment by SpaiR** [comment]
Have you tried to run the editor as an administrator?

**Comment by Delnth** [comment]
Yes, I have specified it in the list of things that I have tried. Administrator mode doesn't change anything. The editor behaves all the same.

**Comment by SpaiR** [comment]
In "strongdmm/bin" folder there is a "sdmmparser.exe" file. Can you try to run in it your console? Should look like this `./sdmmparser.exe full_path_to_dme_file result.json`. As the result you should see `result.json` file with parsed environment.

**Comment by Delnth** [comment]
Which console? The Windows CMD?

**Comment by SpaiR** [comment]
No, I just wanted to ensure that it works. That exe is used by the editor to parse your environment. If you have an endless loading, it could mean that the parser doesn't work. Yet it works. I don't know what kind of problem do you have. Maybe later I will add more logging to the process.

**Comment by callunaborealis** [comment]
I have the exact same issue when:
- using 1.7.1 and a last few older versions
- Windows 10 Home, Administrator mode

So I decided to download the source code for StrongDMM and do a `./gradlew build` and `./gradlew runShadow` from the project root. I was able to build StrongDMM and open the newly built StrongDMM. But when I opened a DME file, it resulted in the same behaviour where the DME is at the "Loading tgstation.dme" indefinitely until I close StrongDMM.

I also noticed this error in the terminal I used (I'm using Gradle 6.6.1):

```
$ ./gradlew runShadow

> Task :runShadow

# After opening desertrose\tgstation.dme...

Exception in thread "Thread-2" java.lang.RuntimeException: Unable to parse environment with path: F:\Code\desertrose\tgstation.dme
        at strongdmm.byond.dme.SdmmParser.parseDme(SdmmParser.kt:40)
        at strongdmm.service.EnvironmentService$openEnvironment$1.invoke(EnvironmentService.kt:33)
        at strongdmm.service.EnvironmentService$openEnvironment$1.invoke(EnvironmentService.kt:16)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

I was able to replicate this same exception in another DME file.

```
$ ./gradlew runShadow

> Task :runShadow
Exception in thread "Thread-2" java.lang.RuntimeException: Unable to parse environment with path: F:\Code\TerraGov-Marine-Corps\tgmc.dme
        at strongdmm.byond.dme.SdmmParser.parseDme(SdmmParser.kt:40)
        at strongdmm.service.EnvironmentService$openEnvironment$1.invoke(EnvironmentService.kt:33)
        at strongdmm.service.EnvironmentService$openEnvironment$1.invoke(EnvironmentService.kt:16)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

I thought maybe it has something to do with `sdmmparser`. So I tried to build the sdmmparser as stated in the README.

I'm using cargo 1.46.0 (149022b1d 2020-07-17).

```
$ cd src/sdmmparser
$ cargo build --verbose
       Fresh cfg-if v0.1.10
       Fresh unicode-xid v0.2.1
       Fresh ppv-lite86 v0.2.9
       Fresh autocfg v1.0.1
       Fresh siphasher v0.3.3
       Fresh adler v0.2.3
       Fresh proc-macro-hack v0.5.18
       Fresh bytemuck v1.4.0
       Fresh interval-tree v0.8.0 (https://github.com/SpaiR/SpacemanDMM?rev=ac037752c930030a46f4ddcb7e39b199246d19d1#ac037752)
       Fresh itoa v0.4.6
       Fresh linked-hash-map v0.5.2 (https://github.com/SpaceManiac/linked-hash-map?branch=get-key-value#7e6de06f)
       Fresh guard v0.5.0
       Fresh phf_shared v0.8.0
       Fresh miniz_oxide v0.4.1
       Fresh proc-macro2 v1.0.19
       Fresh getrandom v0.1.14
       Fresh rgb v0.8.25
       Fresh winapi-x86_64-pc-windows-gnu v0.4.0
       Fresh crc32fast v1.2.0
       Fresh libc v0.2.76
       Fresh quote v1.0.7
       Fresh rand_core v0.5.1
       Fresh winapi v0.3.9
       Fresh num-traits v0.2.12
       Fresh ryu v1.0.5
       Fresh bitflags v1.2.1
       Fresh syn v1.0.39
       Fresh rand_pcg v0.2.1
       Fresh rand_chacha v0.2.2
       Fresh winapi-util v0.1.5
       Fresh flate2 v1.0.17
       Fresh ordered-float v2.0.0
       Fresh serde_derive v1.0.115
       Fresh rand v0.7.3
       Fresh termcolor v1.1.0
       Fresh serde v1.0.115
       Fresh lodepng v3.2.1
       Fresh phf_generator v0.8.0
       Fresh toml v0.5.6
       Fresh serde_json v1.0.57
       Fresh phf_macros v0.8.0
       Fresh phf v0.8.0
   Compiling dreammaker v0.1.0 (https://github.com/SpaiR/SpacemanDMM?rev=ac037752c930030a46f4ddcb7e39b199246d19d1#ac037752)
     Running `rustc --crate-name dreammaker --edition=2018 'C:\Users\callunaborealis\.cargo\git\checkouts\spacemandmm-34efa093c9206ba8\ac03775\src\dreammaker\lib.rs' --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 -C metadata=1233682b9b1addf0 -C extra-filename=-1233682b9b1addf0 --out-dir 'F:\Code\StrongDMM\src\sdmmparser\target\debug\deps' -L 'dependency=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps' --extern 'bitflags=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libbitflags-cbf23335caefa7c2.rmeta' --extern 'guard=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libguard-18d9b364878c7db9.rmeta' --extern 'interval_tree=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libinterval_tree-525fc6225db18823.rmeta' --extern 'linked_hash_map=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\liblinked_hash_map-19f91213ac19a632.rmeta' --extern 'lodepng=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\liblodepng-288c6bfa4639e5ec.rmeta' --extern 'ordered_float=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libordered_float-f548f8682732890d.rmeta' --extern 'phf=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libphf-575dbe2311815047.rmeta' --extern 'serde=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libserde-5cdf91d669072901.rmeta' --extern 'serde_derive=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\serde_derive-effc1e76a6e3222f.dll' --extern 'termcolor=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libtermcolor-92f933db66b99332.rmeta' --extern 'toml=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libtoml-f887ac5956eb1abf.rmeta' --cap-lints allow -L 'native=C:\Users\callunaborealis\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-x86_64-pc-windows-gnu-0.4.0\lib'`
error[E0599]: no method named `to_str` found for reference `&[u8]` in the current scope
   --> C:\Users\callunaborealis\.cargo\git\checkouts\spacemandmm-34efa093c9206ba8\ac03775\src\dreammaker\dmi.rs:288:16
    |
288 |         if key.to_str() == Ok("Description") {
    |                ^^^^^^ method not found in `&[u8]`

error[E0599]: no method named `to_str` found for reference `&[u8]` in the current scope
   --> C:\Users\callunaborealis\.cargo\git\checkouts\spacemandmm-34efa093c9206ba8\ac03775\src\dreammaker\dmi.rs:289:38
    |
289 |             if let Ok(value) = value.to_str() {
    |                                      ^^^^^^ method not found in `&[u8]`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `dreammaker`.

Caused by:
  process didn't exit successfully: `rustc --crate-name dreammaker --edition=2018 'C:\Users\callunaborealis\.cargo\git\checkouts\spacemandmm-34efa093c9206ba8\ac03775\src\dreammaker\lib.rs' --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 -C metadata=1233682b9b1addf0 -C extra-filename=-1233682b9b1addf0 --out-dir 'F:\Code\StrongDMM\src\sdmmparser\target\debug\deps' -L 'dependency=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps' --extern 'bitflags=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libbitflags-cbf23335caefa7c2.rmeta' --extern 'guard=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libguard-18d9b364878c7db9.rmeta' --extern 'interval_tree=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libinterval_tree-525fc6225db18823.rmeta' --extern 'linked_hash_map=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\liblinked_hash_map-19f91213ac19a632.rmeta' --extern 'lodepng=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\liblodepng-288c6bfa4639e5ec.rmeta' --extern 'ordered_float=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libordered_float-f548f8682732890d.rmeta' --extern 'phf=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libphf-575dbe2311815047.rmeta' --extern 'serde=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libserde-5cdf91d669072901.rmeta' --extern 'serde_derive=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\serde_derive-effc1e76a6e3222f.dll' --extern 'termcolor=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libtermcolor-92f933db66b99332.rmeta' --extern 'toml=F:\Code\StrongDMM\src\sdmmparser\target\debug\deps\libtoml-f887ac5956eb1abf.rmeta' --cap-lints allow -L 'native=C:\Users\callunaborealis\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-x86_64-pc-windows-gnu-0.4.0\lib'` (exit code: 1)
```

That's where I am stuck now. Can't get StrongDMM to open DME files.

**Comment by SpaiR** [comment]
@callunaborealis Could you try this thing https://github.com/SpaiR/StrongDMM/issues/63#issuecomment-659469429? If it works and you get a result.json file with a parsed environment, then it seems that sdmmparser, for some reason, is unable to write its result to the file created here https://github.com/SpaiR/StrongDMM/blob/master/src/main/kotlin/strongdmm/byond/dme/SdmmParser.kt#L34 You may try to replace 
```
Files.createTempFile("sdmm.", ".json").toFile()
``` 
with
```
File("path_to_the_file_in_your_system_that_exists_for_sure")
```
and run it again.

**Comment by callunaborealis** [comment]
`$ ./libs/sdmmparser.exe ../desertrose/tgstation.dme result.json`  doesn't seem to log anything or create result.json.

The second option I used both a relative and absolute path to an existing empty `test.json` file at the project root, i.e.

```kt
val tmpFile = File("../../../../../../test.json")
val tmpFile = File("/f/Code/StrongDMM/test.json")
val tmpFile = File("/test.json")
```

Ran ` ./libs/sdmmparser.exe ../desertrose/tgstation.dme` but nothing got logged either.

I tried again but with release, repository all on C:\ too but that didn't work either.

**Comment by PapaSejd** [comment]
Im getting the same issue here, Beestation .dmes will load, but attempting something like Interpost-Hague or TG will cause it to infinite load.

**Comment by callunaborealis** [comment]
Beestation .dmes don't work for my case. So far, I haven't gotten a DME file that I can open without infinitely loading for 1.7.1 or 1.8.0.

I have created a new user in my own computer and tried to run everything on C:\, clean compile and run but I still face the same infinite loading issue.

I did also try using `sdmmlauncher` but got this error prompt and clicking close or OK closed the black window: [Screenshot](https://i.imgur.com/5Uv8pv2.png)

The last working version for me is [0.0.10](https://github.com/SpaiR/StrongDMM/releases/tag/v0.0.10) so I have started trying to use that one for now.

**Comment by callunaborealis** [comment]
Okay, I think I found a possible solution to this.

The issue seems to be caused by `sdmparser.exe`. Since my last working version was [0.0.10](https://github.com/SpaiR/StrongDMM/releases/tag/v0.0.10, what I did was take the 1.8.0 version and replace the `strongdmm-windows/strongdmm/app/sdmparser.exe` with `sdmparser.exe` from my last working version (i.e. [0.0.10](https://github.com/SpaiR/StrongDMM/releases/tag/v0.0.10)).

Only issue so far is that I can't open a second environment in the same session as the second opened environment will result in an infinite loading.

**Comment by PapaSejd** [comment]
@callunaborealis DME loads with your fix, however loading maps causes paths to have to be replaced which shouldnt be occurring

**Comment by PapaSejd** [comment]
@callunaborealis I tried out your fix, using a Bay12 codebase, DME would load but loading any map will cause it to have unknown types even though it will load just fine in DM

**Comment by SpaiR** [comment]
> to have unknown types even though it will load just fine in DM

That happens because version 0.0.10 uses an outdated version of SpacemanDMM, which misses some of important fixes.
I've recompiled  sdmmparser in another way. Can you try this one: https://github.com/SpaiR/StrongDMM/releases/download/v1.8.0/sdmmparser.exe ?

@callunaborealis @PapaSejd

**Comment by PapaSejd** [comment]
@SpaiR Unfortunately it infinite loads.

**Comment by SpaiR** [comment]
@PapaSejd Ok, updated once again. Try it with the same link.

**Comment by PapaSejd** [comment]
@SpaiR Unfortunately loads infinitely again, no crash, error or anything, even on admin mode.

**Comment by callunaborealis** [comment]
@SpaiR Thank you! 👍 Replacing the `sdmmparser.exe` with the one from v1.8.0 works for me.

I've also tested this with a fresh download and extracting of `strongdmm-windows.zip` from [v1.8.0](https://github.com/SpaiR/StrongDMM/releases/tag/v1.8.0). Running `strongdmm-windows/strongdmm/StrongDMM.exe` and opening an environment infinitely opens like the issue I faced in the past. Then I downloaded and replaced `strongdmm-windows/strongdmm/app/sdmmparser.exe` with the standalone `sdmmparser.exe` in the 1.8.0 release.

**Comment by SpaiR** [comment]
@callunaborealis 
> and opening an environment infinitely opens like the issue I faced in the past

That's ok. I've recompiled `sdmmparser.exe` and attached it to the release, so you can download it and replace in the way you did before. If that works for you I'll push a new release this weekend with the updated parser as well.

**Comment by PapaSejd** [comment]
@callunaborealis Which codebase have you been using? I'm still trying on a bay codebase and it wont work, even after doing what you did.

**Comment by callunaborealis** [comment]
@PapaSejd  `tgmc`, `colonial-warfare`, `desertrose`. I've tried BayStation 12 too, and it works and I even managed to open `maps\torch\torch1_deck5.dmm` as an example after doing a fresh compile.

**Comment by Captain277** [comment]
I've been using SDMM for about a week/two weeks. Endless Environment Loading was not an issue for me until yesterday, when SDMM began to stall on opening the same environment I've been opening. I'm running CitadelRP's code. Using Calluna's 0.0.10 fix opened up the environment, but resulted in the same issue PapaSejd experienced. Replacing it with the v1.8.0 parser reverts the issue back to endless loading.

**Comment by buffyuwu** [comment]
could you have it create a logfile for debugging?

**Comment by andrej-hajduk** [comment]
Hello I am having the endless environment loading issue. I am trying to load an old Baystation12 dme but it stays in the loop of perpetual loading. I tried to replace the parser provided in a link above but it did not fix the issue for me.

**Comment by buffyuwu** [comment]
> Hello I am having the endless environment loading issue. I am trying to load an old Baystation12 dme but it stays in the loop of perpetual loading. I tried to replace the parser provided in a link above but it did not fix the issue for me.

try latest

**Comment by AJCM-git** [comment]
I had this issue in linux. It gave the exception
```
Exception in thread "Thread-0" java.io.IOException: Cannot run program "/home/maharba/.strongdmm/bin/strongdmm/lib/sdmmparser": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at strongdmm.byond.dme.SdmmParser.parseDme(SdmmParser.kt:36)
	at strongdmm.service.EnvironmentService$openEnvironment$1.invoke(EnvironmentService.kt:42)
	at strongdmm.service.EnvironmentService$openEnvironment$1.invoke(EnvironmentService.kt:16)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 5 more
```

The solution is to make the files under `.strongdmm/bin/strongdmm/lib/` executable with `chmod +x`

**Comment by Sinbest** [comment]
I'm also having this issue, I'm using fortune13 code, it was working fine a couple of minutes ago, but now it infinite loads for some reason.
