### ISSUE TITLE
Feature Request: Object Instances Tab and Standard Object Instances Tab

### ISSUE THREAD

**Issue by ghost** [SpaiR/StrongDMM#64]
Here's a picture to help illustrate one somewhat annoying issue:

![Untitled](https://user-images.githubusercontent.com/3475562/87852156-901ea600-c8cd-11ea-86f5-3bb687ec50ef.png)

If an item has not been used yet, first the user has to generate all icon states from directions. Then if any instances have their parameters edited, the list will add them as a variant.

This is fine in smaller files, but on larger ones it creates a large amount of spam, especially if you're swapping between various maps often.

So my idea was to have 2 tabs on the object instances window: The first tab would just be what the current window shows (ie. the third picture in the screenshot), and the second tab would only show standard instances generated from icon states (ie. the second picture in the screenshot). Just a nice QoL feature that would make it a bit more efficient working with items that have icon variants.

**Comment by SpaiR** [comment]
Scenario you've described seems applicable for your specific case (when you need to group objects by "icon_state" variable). What about the "dir" variable? Instances could be generate from it too.

I just don't see how it should look at final. Please provide more details about feature you're requesting (mockups would be preferable).

**Comment by twoski** [comment]
Sorry i'll try and make it more understandable.

![87852156-901ea600-c8cd-11ea-86f5-3bb687ec50ef (1)](https://user-images.githubusercontent.com/3475562/87884256-3906f700-c9db-11ea-930f-efc00a5fbc93.png)

**Comment by SpaiR** [comment]
There are codebases, where, for example, different types of "floor" represented with the same object, but with the different icon_state. Thus in your "default icon state instances" they will see the same amount of objects (100+) as usual. What's the point of the feature, you've described, for them?

**Comment by twoski** [comment]
Oh you're right, sorry, i'm confusing icon_state with dir. 

With "dir" you know that there would be at most 8 directions listed, which is useful.
