### ISSUE TITLE
Alphabetizing key-value pairs in TGM map format causes noisy diffs

### ISSUE THREAD

**Issue by warriorstar-orion** [SpaiR/StrongDMM#67]
To reproduce:
1. Use StrongDMM v1.7.1.
2. Open a file in TGM format whose key-value pairs are not alphabetized, e.g. https://github.com/ParadiseSS13/Paradise/commit/e8b64acaab3d72643b58919c5154e2155b3867ad
3. Make a small change and then resave the file in TGM format.

Expected results: unrelated tiles do not have their variables altered, keeping diffs minimal
Actual results: 
![2020-07-21 20_45_29-MINGW64__c_Users_horse_Projects_third_party_Paradise__maps](https://user-images.githubusercontent.com/59303604/88121234-220b0500-cb93-11ea-8acf-d18cf71a0373.png)

**Comment by SpaiR** [comment]
It's an intended behavior. Alphabetized order helps to resolve cases like:
```
"a" = (/obj{dir = 2; icon_state = "icon"})
"b" = (/obj{icon_state = "icon"; dir = 2})
```
From DM perspective those keys has different instance, but they don't.

Vars reordering is a one time operation. In the same way time ago maps were converted from DM to TGM format, now they could be additionally sanitized with sdmm.
