### ISSUE TITLE
Objects with /area later in their path are being displayed in the area layer

### ISSUE THREAD

**Issue by Kubius** [SpaiR/StrongDMM#69]
Example path of an object for which the issue occurs is /obj/blind_switch/area - the object will display only when area display is active (ctrl+1), and is invisible otherwise. The object is still present, and when the layer is active it displays right, so my guess would be some insensitivity in pattern matching.

**Comment by SpaiR** [comment]
fixed in https://github.com/SpaiR/StrongDMM/commit/80000369e5383989e1496d399f812fdba0b7d322
