### ISSUE TITLE
Feature Suggestion: Add option to delete instances from Object Panel and also an option to edit instance variables

### ISSUE THREAD

**Issue by SamuelRowe** [SpaiR/StrongDMM#70]
Title explains mostly all. 
Would be cool if there was an option to delete an instance from the 'Object Viewer' (Deleting all the instances that were placed on the map, too), along with an option to edit the variables(Right click menu on an instance in 'Object Viewer') without having to find the instance on the map.

**Comment by SpaiR** [comment]
duplicates #20 #21
