### ISSUE TITLE
Feature Request: Copy object path

### ISSUE THREAD

**Issue by clement-or** [SpaiR/StrongDMM#79]
It would be cool to have the ability to copy an object's path from the right panel or from the map view in the middle.
It could be an option in the right click context menu.

**Comment by SpaiR** [comment]
There is a gear in the right corner of the object panel. It could be opened and it has a "Copy Type To Clipboard" button.

**Comment by clement-or** [comment]
Gotcha.
I personnally think that adding this option to context menus would be more intuitive and be a small UX improvement, since the copy option is often found in such menus.

**Comment by SpaiR** [comment]
Yeah, sound like a good point.

**Comment by SpaiR** [comment]
Available in the new version.
