### ISSUE TITLE
Stuck on parsing environment

### ISSUE THREAD

**Issue by flufflycthu1u** [SpaiR/StrongDMM#8]
Every version since 0.2 gets stuck on parsing environment for me. Not sure if there are logs somewhere I could provide. The tree does load but the parsing environment popup never closes, not sure whether that is relevant.

**Comment by SpaiR** [comment]
Could you answer several questions?
* Did you try last (0.0.7) version or any since 0.0.4?
* What OS do you have?
* What codebase you are tried to parse?

**Comment by flufflycthu1u** [comment]
1) I have tried 0.3 0.6 and 0.7 and I think 0.4.
2) Win 10 home
3) I have tried TG, para, hippie, and another tg derivative I work on.

**Comment by SpaiR** [comment]
Ok. Then let's try to do the next thing: please download this [exe](https://github.com/SpaiR/StrongDMM/raw/master/libs/sdmmparser.exe), it's an executable which does parsing stuff. You can place it anywhere, but it will be handy if you put it in the root of your BYOND project. Then run from your cmd next command: `sdmmparser.exe path_to_your_dme test.json`. As a result of those steps you should find `test.json` file. If you'll see command line errors, you won't find json file, or json itself would be empty - please report results here. If everything will be fine and exe will work as intended, then you can find my discord (`Despair_#7565`) and we will discuss other steps there.

**Comment by SpaiR** [comment]
Just a conclusion about the issue for thouse who might read it later. The problem was connected with installer. Since of 0.0.8 version I changed the way how installer is bundled, so use it. If you still meat the problem: try to start the editor as an administrator or try to use zipped version instead of the installer.
