### ISSUE TITLE
Feature Request: markers for people that don't want to be converted.

### ISSUE THREAD

**Issue by Nak3rbott** [SpaiR/StrongDMM#83]
simple marker (like revs marker) on people that don't want to get converted on malf AI, revs or cult. I think there's one for cult? I have never seen it, however.

**Comment by SpaiR** [comment]
Your request is not meant to be a request to the editor. The editor is a general tool and has nothing in common with an environment it works with (codebase). It doesn't know anything specific about it. You need to address your request to the repo of your codebase.
