### ISSUE TITLE
Feature Request: Add the option to open multiple DMM's at the same time.

### ISSUE THREAD

**Issue by Nanu308** [SpaiR/StrongDMM#86]
### Feature Request
Being able to open multiple DMM's at the same time from the "File->Open Map..." by selecting multiple at the same time.

Would help when setting up multiple map's or inserts for maps and save some time each time you launch SDMM.

**Comment by SpaiR** [comment]
Can you clarify what do you mean by "open multiple DMM's"? The editor is already opens as many maps as you want. You just switch between them as you will in any other editor of that kind. So what exactly do you mean?

**Comment by Nanu308** [comment]
> 
> 
> Can you clarify what do you mean by "open multiple DMM's"? The editor is already opens as many maps as you want. You just switch between them as you will in any other editor of that kind. So what exactly do you mean?

My bad if it was unclear, what i mean is that i wish to select multiple instances of different DMM's at the same time to open, to hinder going to the menu and opening one DMM at a time in SDMM.

Basically a QOL feature when you work with multiple DMM's at the same time.

**Comment by SpaiR** [comment]
I see. Yeah, I've misunderstood you at first. You're talking about selecting multiple map files in the open map dialog. Yes, it's a good thing to have.
