### ISSUE TITLE
Bug: Undo by Ctrl+Z reverts the wrong thing.

### ISSUE THREAD

**Issue by Nanu308** [SpaiR/StrongDMM#87]
When you revert/undo things in SDMM sometimes it will only revert certain things and not the most recent change you made, only way to fix it is by relaunching SDMM.

I have yet to find out what causes this, but it occurs quite regularly.

**Comment by SpaiR** [comment]
Hi. Thank you for your issue report!
Can you provide more details about steps of how to reproduce the problem? Right now you're literally just saying "sometimes things don't work". This information doesn't help a lot. I've didn't heared any report about problems with undo/redo and in past I've spent a lot of time to make it work properly. So if you have a specific steps to see the problem: please provide them. Otherwise, it would be hard to do anything with it.

**Comment by Nanu308** [comment]
> 
> 
> Hi. Thank you for your issue report!
> Can you provide more details about steps of how to reproduce the problem? Right now you're literally just saying "sometimes things don't work". This information doesn't help a lot. I've didn't heared any report about problems with undo/redo and in past I've spent a lot of time to make it work properly. So if you have a specific steps to see the problem: please provide them. Otherwise, it would be hard to do anything with it.

I'll try and reproduce it this weekend in a reliable way and get it written down here then

**Comment by Nanu308** [comment]
> 
> 
> Hi. Thank you for your issue report!
> Can you provide more details about steps of how to reproduce the problem? Right now you're literally just saying "sometimes things don't work". This information doesn't help a lot. I've didn't heared any report about problems with undo/redo and in past I've spent a lot of time to make it work properly. So if you have a specific steps to see the problem: please provide them. Otherwise, it would be hard to do anything with it.

Here is a video of it occuring, i have been unable to replicate it reliably unfortunatly. Will try and look into it some more, also heard with some other mappers in CM and they have encountered it as well, but they don't know why it happens either.

https://youtu.be/FPsRdy9vMqg

**Comment by SpaiR** [comment]
I see. Ok, thnx for detaild demonstration. I'll look into this problem later for sure.
