### ISSUE TITLE
Windows cannot find 'StrongDMM.exe' Make sure you typed the name correctly, and then try again.

### ISSUE THREAD

**Issue by CitrusGender** [SpaiR/StrongDMM#88]
I would offer steps to reproduce if I could but right now it seems like I have no idea how I got here.

Some possible points:

- I set .dmm files to automatically pull from a strongdmm.exe file that was on my desktop, I may have changed that file around and adjusted the name while I use it.
![image](https://user-images.githubusercontent.com/31262308/120257177-b4714000-c25d-11eb-8447-2c8e4ce49655.png)

I have no idea how to fix it and I haven't seen any previous error report of this. Whenever I remove all copies of StrongDMM on my computer and reinstall: it does the same thing.

**Comment by CitrusGender** [comment]
I got it to run but I had to download the source code. One other thing to note is that I got this when I made C:\Program Files\StrongDMM and put Strong DMM in that file. 

https://feen.us/hpcwrboyvx.mp4

**Comment by 1393F** [comment]
Check your antivirus quarantine

**Comment by ProfessorPopoff** [comment]
I'm late to this. But, around the time this was posted, My anti-virus quarantined it. 🤔 how curious. If you didn't check it, then check it.
