### ISSUE TITLE
[Feature Request] Adding checks of the TG station codebase related to map editing

### ISSUE THREAD

**Issue by Gesugao-san** [SpaiR/StrongDMM#93]
The title speaks for itself. For example: https://github.com/tgstation/tgstation/blob/master/tools/ci/check_grep.sh#L39:
```bash
if grep -P '^/area/.+[\{]' _maps/**/*.dmm;	then
    echo "ERROR: Vareditted /area path use detected in maps, please replace with proper paths."
    st=1
fi;
```

---

if the user does something that meets these checks, then it is worth displaying a sanity warning (with the ability to disable it).

**Comment by SpaiR** [comment]
The editor is not codebase specific and won't be at any point.
