### ISSUE TITLE
Feature Request: Support for FILE_DIR

### ISSUE THREAD

**Issue by Laboredih123** [SpaiR/StrongDMM#96]
Would be quite nice to be able to take clear screenshots of maps. Dream Maker doesn't support screenshots while SDMM breaks since it can't use FILE_DIR.

**Comment by SpaiR** [comment]
It will be a mess to add support for that, since it will require to process code parsing more precisely. Which is avoided, since StrongDMM uses SpacemanDMM to do a parsing.
